#ifndef CTCONFIG_H
#define CTCONFIG_H

//#define ENABLE_ASSERT_CHECKS
//#define CT_NODE_DEBUG
//#define ENABLE_INTEGRITY_CHECK
//#define ENABLE_COUNTERS
//#define ENABLE_PAGING
#define ENABLE_COMPRESSION

#ifdef ENABLE_COMPRESSION
//  #define ENABLE_SPECIALIZED_COMPRESSION
#endif

#endif // CTCONFIG_H
